### PR TITLE
Add example projects

### PR DESCRIPTION
**Pull request by JoviDeCroock**
In the preact repository we are removing a lot of content from our README, I'm adding it here for visibility (+ linking to here) https://github.com/preactjs/preact/pull/2232

### CODE REVIEW

**Comment by ooade** [comment]
Awesome! 🔥
Also, I don't mind transferring the repo's ownership to the Preact organization :)

**Comment by JoviDeCroock** [comment]
@ooade Thanks for the quick reply and merge, I think if we can help you out with maintaining this that would be great! 🎉

**Comment by ooade** [comment]
Alright, then. Thanks 🎉

**Comment by JoviDeCroock** [comment]
Can you do this? I have no access to `settings`.

**Comment by ooade** [comment]
Sure @JoviDeCroock. It would be a lot better to just transfer the ownership so that a wide range of people could be given access to the repository settings.

**Comment by JoviDeCroock** [comment]
@ooade I can do it if I have admin rights on this repository

**Comment by ooade** [comment]
@JoviDeCroock I'm not sure there's a way to grant admin right on a personal repository.
Screenshot 2020-01-06 at 6 44 51 PM

**Comment by ooade** [comment]
Screenshot 2020-01-06 at 8 11 44 PM
Apparently, it's impossible to give admin rights.

**Comment by JoviDeCroock** [comment]
Oh that's annoying :/

**Comment by ooade** [comment]
Yeah 😅
But, if you need me to transfer the repo, I'm all good with it, as well.

**Comment by JoviDeCroock** [comment]
@ooade can you transfer the repo? I think that's the only way

**Comment by ooade** [comment]
Sure. I'll do that now :)

**Comment by JoviDeCroock** [comment]
Thank you! :tada:

**Comment by ooade** [comment]
I need to be added to the organization to transfer it tho.

**Comment by JoviDeCroock** [comment]
Hmm maybe if you transfer to me and I transfer it over since you need admin access on preactjs then

**Comment by ooade** [comment]
Alright! Help delete the one you forked.
Screenshot 2020-01-06 at 9 23 48 PM

**Comment by JoviDeCroock** [comment]
Done

**Comment by ooade** [comment]
There you go :)
Screenshot 2020-01-06 at 9 27 49 PM

**Comment by JoviDeCroock** [comment]
All right, will give you collaborator and stuff as soon as it's on the org

**Pull request merged**
