### PR TITLE
Revert "Add Preact Testing Library"

### PR DESCRIPTION
**Pull request by ooade**
Reverts ooade/awesome-preact#31

### CODE REVIEW

**Comment by antoaravinth** [comment]
Why it is reverted?

**Comment by ooade** [comment]
I already added it 😅

**Comment by ooade** [comment]
Don't mind me. The Awesome Preact Bot malfunctioned and since a log wasn't properly kept, I had to revert and make a new PR to see what went wrong.

**Comment by antoaravinth** [comment]
Awesome! Cool thanks for doing this.

**Pull request merged**
